# -*- coding: utf-8 -*-
"""summarizer_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUx6he4SyYY8FtvPad-es-m3vuhUgbnT

# Multimodal Video Summarization System :

*An AI-powered YouTube video summarizer that converts videos into structured articles*

## 1. Environment Setup & Dependencies :
"""

# !pip install -qU youtube_search
# !pip install -qU youtube-transcript-api
# !pip install -qU langchain_community
# !pip install -qU langchain-text-splitters
# !pip install -qU langchain langchain-groq

"""## 2. Library Imports :"""

import os
# from google.colab import userdata
from dotenv import load_dotenv
load_dotenv()

from langchain_community.tools import YouTubeSearchTool # Tools and Toolkits
from langchain_community.document_loaders import YoutubeLoader # Document Loader

from langchain_groq import ChatGroq

from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_core.runnables import chain, RunnableBranch, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain.agents import create_agent
from langchain.agents.middleware import SummarizationMiddleware

import zipfile

"""## 3. API Configuration :"""

# Groq API Key
groq_key = os.getenv('groq_api')
os.environ['GROQ_API_KEY'] = groq_key

"""YouTube Search package searches YouTube videos avoiding using their ₹heavily rate-limited API₹. It uses the form on the YouTube homepage and scrapes the resulting page.

## 4. YouTube Search Tool :
"""

tool = YouTubeSearchTool()
tool

results = tool.run("Math for Machine Learning")
results

len(results)

"""## 5. Transcript Loading (Initial Testing) :"""

loader = YoutubeLoader.from_youtube_url(
    "https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS"
)
loader

text = loader.load()
text

text[0].page_content

len(text[0].page_content)

len(text[0].page_content.split())

"""## 6. LLM Initialization :"""

llm = ChatGroq(
    model="llama-3.1-8b-instant"
)
llm

"""## 7. Prompt for Tool Routing :"""

human_template = '''
"""DO NOT SUMMARIZE, ANALYZE, OR PROCESS.

**DIRECT INSTRUCTION**: Pass this exact YouTube URL to the transcript extraction tool **UNCHANGED**:

{youtube_link}

**CRITICAL**: Use the URL exactly as provided. No modifications, no explanations, no additional text.
'''
tool_prompt = ChatPromptTemplate.from_messages([
    HumanMessagePromptTemplate.from_template(human_template)
])
tool_prompt

"""## 8. Transcript Extraction Module :


"""

import zipfile
transcript_cache = {}

def extract_transcript(link: str) -> str:
  try :
      if link in transcript_cache:
          return transcript_cache[link]

      loader = YoutubeLoader.from_youtube_url(link)
      docs = loader.load()
      transcript = docs[0].page_content

      transcript_cache[link] = transcript
      return transcript
  except Exception as e:
      print(f"Error extracting transcript: {e}")
      return ""

extract_transcript('https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS')

"""## 9. Transcript Processing Chains :"""

transcript_chain =RunnableLambda(extract_transcript)
transcript_chain

transcript_chain.invoke('https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS')

extract_transcript_chain = RunnablePassthrough() |  RunnableLambda(extract_transcript)
extract_transcript_chain

extract_transcript_chain.invoke('https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS')

"""## 10. Short Transcript Summarization :"""

system_message = 'You are an Professional Article Writer specializing in writing articles for Medium, LinkedIn, and tech blogs.'

human_message = '''
Transform YouTube transcript into **engaging, professional articles** with:

**CRITICAL INSTRUCTIONS**:
- **IGNORE** Introductionary notes like welcome, In this video
- **IGNORE** all channel names, "subscribe", "like", "comment", "follow", "check description"
- **IGNORE** marketing phrases: "my course", "my discord", "affiliate links", "sponsors"
- **FOCUS ONLY** on technical content, code, tutorials, actionable insights

**MANDATORY ARTICLE STRUCTURE** (exact Medium/LinkedIn format):
- Write in **first-person professional tone**
- Use **bold subheadings**, **numbered lists**.
- Include **code snippets** for technical videos
- Make **Actionable Steps** copy-paste ready
- End with **short summary of the article**
{transcript}
'''
summarizer_prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template(system_message),
    HumanMessagePromptTemplate.from_template(human_message)
])
summarizer_prompt

# Base summarization chain for short transcripts
base_summarizer = RunnablePassthrough() | RunnableLambda(extract_transcript) | summarizer_prompt | llm | StrOutputParser()
base_summarizer

response = base_summarizer.invoke('https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS')
response

print(response)

"""## 11. Recursive Summarization Setup :"""

recursive_system_prompt = """
You are a recursive summarization engine.

Your job:
- Continuously summarize incoming content
- Maintain a concise but complete running summary
- When content grows large, compress older information
- Preserve key technical details, concepts, and relationships
- Output ONLY the updated summary

Think of this as:
A rolling summary that improves as more text arrives and prepares a production ready article.
"""

def get_text_chunks(text, chunk_size=4000, chunk_overlap=200, length_threshold=1000):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ".", " ", ""],  # priority order
    )
    return splitter.split_text(text)

# Agent setup
agent = create_agent(
    model=llm,
    tools=[],   # NO tools - summarization ONLY
    system_prompt = recursive_system_prompt,
    middleware=[
        SummarizationMiddleware(
            model=llm,
            trigger=("tokens", 1000),     # Summarize when conversation hits 1000 tokens
            keep=("tokens", 200),        # Preserve last 200 tokens verbatim
        ),
    ],
)
agent

"""## 12. Long Transcript Summarization Logic :"""

def recursive_summarize(text, agent=agent):
    chunks = get_text_chunks(text)
    running_summary = ""

    for chunk in chunks:
        response = agent.invoke({
            "messages": [
                {
                    "role": "user",
                    "content": f"""
You are summarizing technical content.

Current summary:
{running_summary}

New content:
{chunk}

While summarizing teh text in the form of article strictly follow
**CRITICAL INSTRUCTIONS**:
- **IGNORE** Introductionary notes like welcome, In this video
- **IGNORE** all channel names, "subscribe", "like", "comment", "follow", "check description"
- **IGNORE** marketing phrases: "my course", "my discord", "affiliate links", "sponsors"
- **FOCUS ONLY** on technical content, code, tutorials, actionable insights

**MANDATORY ARTICLE STRUCTURE** (exact Medium/LinkedIn format):
- Write in **first-person professional tone**
- Use **bold subheadings**, **numbered lists**.
- Include **code snippets** for technical videos
- Make **Actionable Steps** copy-paste ready
- End with **short summary of the article**
"""
                }
            ]
        })

        running_summary = response["messages"][-1].content

    return running_summary

long_summarizer = RunnablePassthrough() | RunnableLambda(extract_transcript) | RunnableLambda(recursive_summarize)
long_summarizer

response = long_summarizer.invoke('https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS')
response

print(response)

"""## 13. Smart Routing (Dynamic Selection) :"""

# RUNNABLE BRANCH - Routes automatically based on transcript length
def estimate_transcript_length(link: str) -> bool:
    """Quick length estimator (characters → tokens)."""
    transcript = extract_transcript(link)
    return len(transcript.split()) >= 1000

estimate_transcript_length('https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS')

smart_summarizer = RunnableBranch(
    # Condition: if transcript ≥ 1000 words → long handler
    (RunnableLambda(estimate_transcript_length), long_summarizer),

    # Else: base summarizer for short transcripts
    base_summarizer)

# Usage - Single invoke handles ALL lengths automatically
article = smart_summarizer.invoke("https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS")
article

"""## 14. Frontend Generation Prompt :"""

system_message = """You are a Senior Frontend Web Developer with 10+ years experience in HTML5, CSS3, and modern JavaScript (ES6+).

Your task: Generate COMPLETE, PRODUCTION-READY frontend code based on user requirements.

MANDATORY DESIGN REQUIREMENTS:
- Dark theme ONLY (no light theme)
- Background: #0d1117 or similar dark color
- Text: light colors (#e6edf3)
- Use modern UI like Medium / Dev.to (dark mode)
- Clean typography and spacing
- Smooth scrolling and subtle animations

**MANDATORY OUTPUT FORMAT** (exact delimiters):
--html--
[html code here]
--html--

--css--
[css code here]
--css--

--js--
[java script code here]
--js--

STRICT RULES:
1. You MUST output ALL THREE sections:
   --html--
   --css--
   --js--

2. Do NOT skip any section
3. Do NOT change delimiters
4. Do NOT add explanation text
5. Output ONLY code

FAILURE TO FOLLOW = INVALID OUTPUT
"""

human_message = '''
Create a **production-ready article webpages** in the style of **Medium, Dev.to, Hashnode, and Substack**.

**MANDATORY REQUIREMENTS**:
- **Mobile-first responsive design** (perfect on all devices)
- **Clean, modern typography** (system fonts + readability first)
- **Medium-like article layout** with card-based design
- **Dark/light theme toggle**
- **Smooth animations** and **scroll effects**
- **SEO optimized** with proper meta tags
- **Accessibility compliant** (ARIA labels, keyboard navigation)

**CONTENT TO USE**: {article_content}
'''

web_dev_template = ChatPromptTemplate.from_messages([system_message, human_message])
web_dev_template

"""## 15. Webpage Generation Chain :"""

webpage_chain = web_dev_template | llm | StrOutputParser()
webpage_chain

response = webpage_chain.invoke({'article_content': article})
response

"""## 16. Final End-to-End Pipeline :"""

smart_summarizer = RunnableBranch(
    # Condition: if transcript ≥ 1000 words → long handler
    (RunnableLambda(estimate_transcript_length), long_summarizer),

    # Else: base summarizer for short transcripts
    base_summarizer) | web_dev_template | llm | StrOutputParser()
smart_summarizer

"""## 17. Guard Layer (Error Handling) :"""

def safe_summarize(link):
    transcript = extract_transcript(link)

    if transcript.startswith("ERROR"):
        return transcript

    return smart_summarizer.invoke(link)

"""## 18. Code Extraction (HTML/CSS/JS Parsing) :"""

article = smart_summarizer.invoke("https://youtu.be/1UKr6BhCCdg?si=KW-_1Wgpf1I8TcaS")
article

"""## 19. File Generation & Export :"""

def extract_code_sections(response):
    try:
        if '--html--' not in response or '--css--' not in response or '--js--' not in response:
            print("⚠️ Missing expected sections in response")
            return None, None, None

        html = response.split('--html--')[1].split('--css--')[0].strip()
        css = response.split('--css--')[1].split('--js--')[0].strip()
        js = response.split('--js--')[1].strip()

        return html, css, js

    except Exception as e:
        print("❌ Parsing failed:", e)
        return None, None, None


html_content, css_content, js_content = extract_code_sections(article)

if not html_content:
    print("Output format issue. Try again.")
else:
    with open('index.html', 'w') as f:
        f.write(html_content)

    with open('style.css', 'w') as f:
        f.write(css_content)

    with open('script.js', 'w') as f:
        f.write(js_content)

    import zipfile
    with zipfile.ZipFile('Website.zip', 'w') as zipf:
        zipf.write('index.html')
        zipf.write('style.css')
        zipf.write('script.js')